version: '3.8'
services:
  db-migrator:
    build: ./backend
    command: python -c "from src.database import Base, engine; from src.models import models; Base.metadata.create_all(bind=engine)"
    volumes:
      - db_data:/app/sql_data
  backend:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - RELOAD=true
      - APP_MODULE=src.api.main:app
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app          # mount your live code
      - db_data:/app/sql_data   # share DB storage only
    depends_on:
      - db-migrator
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"

volumes:
  db_data: